const canvas=document.getElementById('matrixCanvas');const ctx=canvas.getContext('2d');let matrixEnabled=!0;function resizeCanvas(){canvas.width=window.innerWidth;canvas.height=window.innerHeight}
resizeCanvas();window.addEventListener('resize',resizeCanvas);const katakana='アカサタナハマヤラワガザダバパイキシチニヒミリギジヂビピウクスツヌフムユルグズヅブプエケセテネヘメレゲゼデベペオコソトノホモヨロヲゴゾドボポヴッ';const latin='ABCDEFGHIJKLMNOPQRSTUVWXYZ';const nums='0123456789';const alphabet=katakana+latin+nums;const fontSize=16;const columns=canvas.width/fontSize;const rainDrops=[];for(let x=0;x<columns;x++){rainDrops[x]=1}
function drawMatrix(){if(!matrixEnabled)return;ctx.fillStyle='rgba(0, 0, 0, 0.05)';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(0, 255, 0, 0.35)';ctx.font=fontSize+'px monospace';for(let i=0;i<rainDrops.length;i++){const text=alphabet.charAt(Math.floor(Math.random()*alphabet.length));ctx.fillText(text,i*fontSize,rainDrops[i]*fontSize);if(rainDrops[i]*fontSize>canvas.height&&Math.random()>0.975){rainDrops[i]=0}
rainDrops[i]++}}
function animate(){drawMatrix();requestAnimationFrame(animate)}
animate();function glitchEffect(element){const originalText=element.textContent;const glitchChars='!<>-_\\/[]{}—=+*^?#________';let iterations=0;const interval=setInterval(()=>{element.textContent=originalText.split('').map((char,index)=>{if(index<iterations){return originalText[index]}
return glitchChars[Math.floor(Math.random()*glitchChars.length)]}).join('');if(iterations>=originalText.length){clearInterval(interval)}
iterations+=1/3},30)}
document.querySelectorAll('h1, h2, h3').forEach(heading=>{heading.addEventListener('mouseover',()=>glitchEffect(heading))});function reveal(){const reveals=document.querySelectorAll(".reveal");for(let i=0;i<reveals.length;i++){const windowHeight=window.innerHeight;const elementTop=reveals[i].getBoundingClientRect().top;const elementVisible=150;if(elementTop<windowHeight-elementVisible){reveals[i].classList.add("active")}else{reveals[i].classList.remove("active")}}}
window.addEventListener("scroll",reveal);document.querySelectorAll('nav a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();document.querySelector(this.getAttribute('href')).scrollIntoView({behavior:'smooth'})})});const form=document.getElementById('contact-form');if(form){form.addEventListener('submit',function(e){e.preventDefault();const name=document.getElementById('name').value;const email=document.getElementById('email').value;const message=document.getElementById('message').value;if(name&&email&&message){alert('Message sent successfully!');form.reset()}else{alert('Please fill in all fields.')}})}
window.addEventListener('scroll',function(){const header=document.querySelector('header');const scrollPosition=window.scrollY;header.style.backgroundPositionY=-scrollPosition*0.5+'px'});const projectItems=document.querySelectorAll('#projects .grid-item');projectItems.forEach(item=>{item.addEventListener('click',function(){this.classList.toggle('expanded')})});function typeWriter(element,text,speed){let i=0;function type(){if(i<text.length){element.innerHTML+=text.charAt(i);i++;setTimeout(type,speed)}}
type()}
const introText=document.querySelector('#introduction p');if(introText){const text=introText.innerHTML;introText.innerHTML='';typeWriter(introText,text,50)}
document.querySelectorAll('section').forEach(section=>{section.classList.add('reveal')});reveal();document.addEventListener("DOMContentLoaded",function(){const lazyImages=[].slice.call(document.querySelectorAll("img.lazy"));if("IntersectionObserver" in window){let lazyImageObserver=new IntersectionObserver(function(entries,observer){entries.forEach(function(entry){if(entry.isIntersecting){let lazyImage=entry.target;lazyImage.src=lazyImage.dataset.src;lazyImage.classList.remove("lazy");lazyImageObserver.unobserve(lazyImage)}})});lazyImages.forEach(function(lazyImage){lazyImageObserver.observe(lazyImage)})}})